function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(DWARF.LineTableSupport.step, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, DWARF.LineTableSupport.StateMachine,))
    precompile(DWARF.Attributes.readorskip, ( DWARF.LightDIERef, UInt8, Symbol, Base.Val{:skip},))
    precompile(DWARF.read, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, Type{DWARF.SLEB128},))
    precompile(DWARF.Attributes.readorskip, ( DWARF.LightDIERef, UInt8, Symbol, Base.Val{:read},))
    precompile(DWARF.seekentry, ( DWARF.LightDIERef,))
    precompile(DWARF.LineTableSupport.Type, (Type{DWARF.LineTableSupport.RegisterState}, Bool,))
    precompile(DWARF.LineTableSupport.unpack, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, Type{DWARF.LineTableSupport.HeaderStub},))
    precompile(DWARF.LineTableSupport.pc_adv!, ( DWARF.LineTableSupport.StateMachine, Base.GMP.BigInt,))
    precompile(DWARF.LineTableSupport.pc_adv!, ( DWARF.LineTableSupport.StateMachine, UInt8,))
    precompile(DWARF.read, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, Type{DWARF.ULEB128},))
    precompile(DWARF.LineTableSupport.pc_adv!, ( DWARF.LineTableSupport.StateMachine, Int64,))
    precompile(DWARF.decode, ( Array{UInt8, 1}, Int64, Type{DWARF.SLEB128}, DataType,))
    precompile(DWARF.LineTableSupport.decode_next, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, DWARF.LineTableSupport.Header{UInt32},))
    precompile(DWARF.LineTableSupport.Type, (Type{DWARF.LineTableSupport.FileEntry}, UTF8String, Int64, Int64, Int64,))
    precompile(DWARF._searchforip, ( DWARF.UnitIterator{DWARF.DWARFCUHeader}, UInt64,))
    precompile(DWARF.LineTableSupport.readstring, ( Base.AbstractIOBuffer{Array{UInt8, 1}},))
    precompile(DWARF.skip_children, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, DWARF.LightDIERef,))
    precompile(DWARF.next, ( DWARF.UnitIterator{DWARF.DWARFCUHeader}, UInt64,))
    precompile(DWARF._searchforip, ( DWARF.ChildIterator, UInt64,))
    precompile(DWARF.Expressions.evaluate_generic, ( DWARF.Expressions.StateMachine{UInt64}, Array{UInt8, 1}, Any, Any, Any, Symbol,))
    precompile(DWARF.Expressions.Type, (Type{DWARF.Expressions.StateMachine{UInt64}},))
    precompile(DWARF.extract_attribute, ( DWARF.LightDIERef, UInt8, Symbol,))
    precompile(DWARF.size_to_inttype, ( UInt8,))
    precompile(DWARF.LineTableSupport.next, ( DWARF.LineTableSupport.LineTable, DWARF.LineTableSupport.StateMachine,))
    precompile(DWARF.Attributes.readorskip, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, Type{DWARF.ULEB128}, Symbol, Base.Val{:skip},))
    precompile(DWARF.pc_range, ( DWARF.LightDIERef,))
    precompile(DWARF.read, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, Type{DWARF.AbbrevTableEntry}, Symbol,))
    precompile(DWARF.LineTableSupport.Type, (Type{DWARF.LineTableSupport.HeaderStub{UInt32}}, UInt32, UInt16, UInt32, UInt8, Int64, UInt8, Int8, Int8, UInt8,))
    precompile(DWARF.zero, ( Type{DWARF.AttributeSpecification},))
    precompile(DWARF.Expressions.evaluate_simple_location, ( DWARF.Expressions.StateMachine{UInt64}, Array{UInt8, 1}, Any, Any, Any, Symbol,))
    precompile(DWARF.start, ( DWARF.ChildIterator,))
    precompile(DWARF.LineTableSupport.start, ( DWARF.LineTableSupport.LineTable,))
    precompile(DWARF.LineTableSupport.read, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, Type{DWARF.LineTableSupport.FileEntry},))
    precompile(DWARF.Type, (Type{DWARF.AttributeSpecification}, UInt64, UInt8,))
    precompile(DWARF.LineTableSupport.read_header, ( Base.AbstractIOBuffer{Array{UInt8, 1}},))
    precompile(DWARF.LineTableSupport.state_step, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, DWARF.LineTableSupport.StateMachine,))
    precompile(DWARF.LineTableSupport.Type, (Type{DWARF.LineTableSupport.Header{UInt32}}, DWARF.LineTableSupport.HeaderStub{UInt32}, Array{UInt8, 1}, Array{UTF8String, 1}, Array{DWARF.LineTableSupport.FileEntry, 1},))
    precompile(DWARF.Type, (Type{DWARF.LightDIERef}, Base.AbstractIOBuffer{Array{UInt8, 1}}, DWARF.CU, Int64,))
    precompile(DWARF.Type, (Type{DWARF.LightDIERef}, Base.AbstractIOBuffer{Array{UInt8, 1}}, DWARF.CU, UInt64,))
    precompile(DWARF.read, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, Type{DWARF.DWARFCUHeader}, Symbol,))
    precompile(DWARF.Attributes.readorskip, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, Type{UInt32}, Symbol, Base.Val{:read},))
    precompile(DWARF.LineTableSupport.header_type, ( DWARF.LineTableSupport.HeaderStub{UInt32},))
    precompile(DWARF.Attributes.Type, (Type{DWARF.Attributes.SectionReference}, UInt32,))
    precompile(DWARF.Attributes.readorskip, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, Type{UInt64}, Symbol, Base.Val{:skip},))
    precompile(DWARF.Attributes.Type, (Type{DWARF.Attributes.DwarfExpr{UInt64}}, Array{UInt8, 1},))
    precompile(DWARF.Attributes.readorskip, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, Type{UInt32}, Symbol, Base.Val{:skip},))
    precompile(DWARF.LineTableSupport.header_type, ( DWARF.LineTableSupport.Header{UInt32},))
    precompile(DWARF.Attributes.Type, (Type{DWARF.Attributes.StrTableReference}, UInt32,))
    precompile(DWARF.Type, (Type{DWARF.ULEB128}, Base.GMP.BigInt,))
    precompile(DWARF.Attributes.convert, ( Type{UInt64}, DWARF.Attributes.SectionReference,))
    precompile(DWARF.readnthattr, ( DWARF.LightDIERef, DWARF.AbbrevTableEntry, Symbol, Int64,))
    precompile(DWARF.read, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, Type{DWARF.AbbrevTableSet}, Symbol,))
    precompile(DWARF.Attributes.Type, (Type{DWARF.Attributes.DwarfExpr{UInt64}}, Void,))
    precompile(DWARF.skip_attributes, ( DWARF.LightDIERef, DWARF.AbbrevTableEntry,))
    precompile(DWARF.LineTableSupport.Type, (Type{DWARF.LineTableSupport.LineTable}, Base.AbstractIOBuffer{Array{UInt8, 1}},))
    precompile(DWARF.searchspforip, ( DWARF.LightDIERef, UInt64,))
    precompile(DWARF.extract_attribute, ( DWARF.LightDIERef, UInt8,))
    precompile(DWARF.Attributes.readorskip, ( Base.AbstractIOBuffer{Array{UInt8, 1}}, Type{UInt64}, Symbol, Base.Val{:read},))
end
